### PR TITLE
fix: file extension stripping in writeTypes function

### PR DESCRIPTION
**Pull request by productdevbook**
### ❓ Type of change

```
  const connectPostgresJS: typeof import('../../../../node_modules/.pnpm/@pergel+nuxt@0.7.19_nuxt@3.9.3_rollup@4.9.6_vite@5.0.12_vue@3.4.15/node_modules/@pergel/nuxt/dist/runtime/modules/drizzle/drivers/postgres/export.mjs')['connectPostgresJS']
  ```
  
fixed pr

```
  const connectPostgresJS: typeof import('../../../../node_modules/.pnpm/@pergel+nuxt@0.7.19_nuxt@3.9.3_rollup@4.9.6_vite@5.0.12_vue@3.4.15/node_modules/@pergel/nuxt/dist/runtime/modules/drizzle/drivers/postgres/export')['connectPostgresJS']
```

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — CHANGES_REQUESTED** [review]
We need to keep the isDirectory check or it will strip dots from folders.

**Comment by productdevbook** [comment]
@danielroe fixed.

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Thank you ❤️

**Review by pi0 — APPROVED** [review]
Nice find!

**Pull request merged**
