### PR TITLE
perf(cloudflare): check for asset url

### PR DESCRIPTION
**Pull request by Hebilicious**
Remove KV access when an API route is called.

### 🔗 Linked issue

Fix https://github.com/unjs/nitro/issues/1001
Resolves https://github.com/unjs/nitro/issues/1235

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Hebilicious** [comment]
I'm not 100% sure this works yet, and it doesn't look like the test case are very useful there. Extending them.

This was useful to debug :
```ts
  const list = await env.__STATIC_CONTENT.list();
  console.log("GET ASSET FROM KV", list.keys.map((k) => k.name), { publicAssetBases });
```

Should we add e2e tests ? Especially Nuxt ones. IE deploy nuxt project with nitro + wrangler and hit the endpoints.

**Comment by pi0** [comment]
Can you please explain more what routes are not being matched?

**Comment by Hebilicious** [comment]
Sure ! For the Cloudflare Module for example : 

Running the tests with isInPublicAssets
image

Running the tests with isInKv
image

**Comment by pi0** [comment]
Good point about also checking `.html` suffixes. Since we are checking for public asset existence in other presets, it would be much better if we could merge `isInKV` functionality into `isPublicAssetURL`. Otherwise seems really good improvements 💯

**Comment by Hebilicious** [comment]
> Good point about also checking `.html` suffixes. Since we are checking for public asset existence in other presets, it would be much better if we could merge `isInKV` functionality into `isPublicAssetURL`. Otherwise seems really good improvements 💯

This was done in the later commits. Reminder to review again 🙏🏽

**Comment by pi0** [comment]
Thanks for changes. As an update, i still need to revisit this issue while it is important fix and i value your efforts, i am still not convinced why we are introducing a new util like this so need to check it more in depth (i might be wrong as well!)

**Comment by Hebilicious** [comment]
> Thanks for changes. As an update, i still need to revisit this issue while it is important fix and i value your efforts, i am still not convinced why we are introducing a new util like this so need to check it more in depth (i might be wrong as well!)

Now that look more at it, this PR is more of a fix than a perf, as currently there's a bug where some matched assets aren't returned by KV, and some non existing assets are being accessed.

**Comment by zsilbi** [comment]
This would be a very nice improvement!
I found this as I was investigating why my noop endpoint latency is so unpredictable. (bottom)

kv_asset

**Comment by pi0** [comment]
With [workers static assets](https://developers.cloudflare.com/workers/static-assets/) we won't need to depend on binding anymore.

**Pull request closed without merging**
