### PR TITLE
feat: add `flightcontrol` preset

### PR DESCRIPTION
**Pull request by bahdcoder**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This change adds a new deployment provider to Nitro: deploying to AWS via Flightcontrol. Flightcontrol helps you deploy your Nitro projects (Both static & SSR) to your own AWS account with little to no configuration.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
This is amazing. Do you mind to add a dedicated `flightcontrol` to the presets too? (https://github.com/unjs/nitro/tree/main/src/presets)

**Comment by bahdcoder** [comment]
Thanks @pi0 . Absolutely. Will ping soon once I have the update.

**Comment by bahdcoder** [comment]
@pi0 I added the preset. Can you please double check if all looks okay?

**Comment by ModupeD** [comment]
This should be closed, I opened a new request for the docs to be added here: https://github.com/unjs/nitro/pull/1250

**Pull request merged**
