### PR TITLE
feat: add `types:extend` hook

### PR DESCRIPTION
**Pull request by mukundshah**
### 🔗 Linked issue
https://github.com/unjs/nitro/issues/1710

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mukundshah** [comment]
@pi0 any update on this?

**Comment by pi0** [comment]
@mukundshah Sorry for delay it is on my check list to review asap for next minor 👍🏼

**Comment by mukundshah** [comment]
@pi0 no worries; Thank you for reply and update ;)

**Comment by pi0** [comment]
Sure we can wait. Also this is an object we are passing so if you are generally okay with naming, we can merge and iterate to extend it later. Please let me know which method you prefer.

**Comment by danielroe** [comment]
Your thought on naming seems good to me :+1:
And I'm happy to merge + iterate.

**Pull request merged**
