### PR TITLE
fix(options):  correct `include` empty value

### PR DESCRIPTION
**Pull request by cinob**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

If `include` is omitted or has zero length, filter will return `true` by default.
Resulted in scanning the entire directory.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Hi dear @cinob and thanks for PR. We currently reverted this bits of code as hotfix (see #294).

I think you discovered a potential bug in underlying [unjs/unimport](https://github.com/unjs/unimport) library that with an empty array implicitly is changing the behavior. Do you think we can move it there? /cc @antfu

**Comment by antfu** [comment]
I wouldn't actually consider it a bug, as `undefined` should be treated differently from `[]`. To me `undefined` means to use the default value, while `[]` indicates that users want to override the default as empty. Otherwise, there would be no way to override the default.

**Comment by pi0** [comment]
But `include: []` shouldn't mean including everything either! What do you mean by overriding default? It can be something like `include: true` if you are thinking of such behavior.

**Comment by pi0** [comment]
Thanks for the reference @antfu. Shall we make it more semantic for unimport? I can understand that it is the behavior of used rollup filter util but their API is not semantic that caused a wrong use by us and also needs a patch similar to this PR to just overcome. (regardless we could improve _exclude_ pattern to improve).

**Comment by pi0** [comment]
Makes sense @antfu. Did you had a chance to work on it?

**Comment by antfu** [comment]
@pi0 included in `unimport@0.4.4`

**Comment by pi0** [comment]
Thanks. I think we then don't need this fix here since unimport should already use defaults with length:0

**Pull request closed without merging**
