### PR TITLE
feat(routeRules): allow wildcard redirects

### LINKED ISSUE #1748: Wildcard redirects
### Describe the feature

If the target URL ends with `/**`, treat it as wildcard redirect and append the subpath properly.

```ts
  routeRules: {
    '/single/': { redirect: { to: '/single-2/', statusCode: 301 } }, // Works 
    '/wildcard/**': { redirect: { to: '/single/', statusCode: 301 } }, // Works
    '/wildcard/**': { redirect: { to: '/wildcard-2/**', statusCode: 301 } }, // Does not work but would be nice
  },
```

`wildcard/a` -> `wildcard-2/a`

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by JaZo**
### 🔗 Linked issue

#1748

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR adds support for wildcard redirects in routeRules:
```
  routeRules: {
    '/wildcard/**': { redirect: { to: '/wildcard-2/**', statusCode: 301 } },
  },
```

It also keeps query parameters, just like the proxy does.

Resolves #1748.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JaZo** [comment]
Ahh the presets, yes! Forgot about them as we don't use any of those. I'll see if I can add this, but that will probably take a while.

**Comment by pi0** [comment]
Good point regarding platform support. It is not necessary however we can iterate and support it later in the future as mainly nitro server should be able to (universally) catch any platform-unsupported patteren.

**Comment by manniL** [comment]
@pi0 I agree. Happy to add it later and let nitro handle it for now 👍🏻

**Comment by Anoesj** [comment]
Nice! It would be fantastic if this could be merged soon. Adding some tests would probably be a good idea.

**Comment by JaZo** [comment]
I've added tests and implemented Netlify and Vercel as these tests failed!

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks for quality changes ❤️

**Pull request merged**
