### PR TITLE
feat: add koyeb preset

### PR DESCRIPTION
**Pull request by imchairmanm**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a basic preset to for [Koyeb](https://www.koyeb.com/).  Includes documentation to build and deploy using both Koyeb's control panel and CLI tool.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Hebilicious — CHANGES_REQUESTED** [review]
For the sake of being thorough, we could add the instructions for deploying with Docker too https://www.koyeb.com/docs/deploy/nuxt#deploy-to-koyeb-using-a-pre-built-container

**Review by Hebilicious — APPROVED** [review]

**Comment by Atinux** [comment]
Wondering if this is necessary to create a `koyeb` preset since it is juste the `node-server` preset.

Adding documentation though is nice.

**Comment by Hebilicious** [comment]
@pi0 I don't think generating a docker file makes sense as they're only used for custom koyeb builds/deployments, and a zero config deployment can be done without one (just the cli commands)

**Review by pi0 — APPROVED** [review]
Sorry it got delayed. Let's progress 👍🏼

**Pull request merged**
