### PR TITLE
fix(deno): implement readAsset

### PR DESCRIPTION
**Pull request by so1ve**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by so1ve** [comment]
I'm not sure if path.join should be used instead of hardcoded id.

**Review by pi0 — APPROVED** [review]
Thanks!

**Comment by pi0** [comment]
> I'm not sure if path.join should be used instead of hardcoded id.

id should be already normalized when passed to bundle. would be nice to double check it for windows however

> Also, it seems that process.env is not replaced by Deno.env.toObject() in the deno press

Yeah we still need unenv/nitro preset for polyfills @danielroe is working on it. Feel free to open an issue for it.

**Comment by so1ve** [comment]
Hi @pi0,
actually deno provides official polyfills here: https://deno.land/std/node

**Comment by pi0** [comment]
yes, std is what we need to port as unenv preset for mapping.

**Pull request merged**
