### PR TITLE
fix: add production export condition to commands

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/framework/issues/8362

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

As we trace dependencies via the `production` export condition, if users do not run their node output with that condition, it may cause issues for them. We may add the condition to our documentation and preview commands to prevent these issues (and possibly overall increase performance).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
Production deployments should be launched with the condition as well.

**Comment by pi0** [comment]
Is there an argument for example for vercel to do it?

**Comment by danielroe** [comment]
I'm not sure. I'll follow up with them directly. But I would _guess_ that setting a `NODE_OPTIONS` environment variable would allow it to be done.

**Comment by danielroe** [comment]
... and I believe we can do that from the FS API. Will check. Shall I add to this PR or make a separate one?

**Comment by pi0** [comment]
Indeed we may find solutions per (some) providers too. My point is, probably right solution instead of requiring the condition is to rewrite written `package.json` exports to make `production` default. We are already doing copy it is not that hard and is a universal fix.

**Comment by danielroe** [comment]
Sounds like a good idea 👍

**Comment by pi0** [comment]
I think we can rework this with new externals plugin and fine-gained access to package.json writing. https://github.com/unjs/nitro/issues/844 (feel free to pick it)

**Pull request closed without merging**
