### PR TITLE
feat(cluster): `node-cluster` preset

### PR DESCRIPTION
**Pull request by Mastercuber**
### 🔗 Linked issue

#451

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Mastercuber** [comment]
How can I link the cloned nitro into a local nuxt-app for testing? Is `npm link /path/to/nitro` in the nuxt-app root enough?
In the [docs](https://v3.nuxtjs.org/guide/deploy/presets/) I can read that the preset can be used with
```js
export default {
  nitro: {
    preset: 'node-cluster'
  }
}
```

**Comment by stafyniaksacha** [comment]
@Mastercuber You can use `link:` or `file:` protocol in `package.json` 💪 

```json
{
  "devDependencies": {
    "bar": "file:/path/to/nitro"
  }
}
```

**Comment by Mastercuber** [comment]
the key is `nitropack` I guess.

**Comment by Mastercuber** [comment]
I'm unable to get a running nuxt app for now. Maybe @pi0 could point me in the right direction.

A new file called `node-cluster.mjs` and the types are built for now, but the content is still a copy of `node-server.ts`.
Another way to built I thought could be to create a rollup plugin. I'm not sure, if this is correctly defined.

A preset was also created but the paths could be incorrect.

Also a worker file could be created to point to when calling `cluster.setupPrimary` but how to integrate a worker file (placing it under `src/runtime/` or add it to `build.config.ts` ?).

**Comment by Mastercuber** [comment]
Now, creating a nuxt app with `npx nuxi init nuxt-app`, adding following to the nuxt config:
```js
nitro: {
  preset: 'node-cluster',
  output: {
    dir: resolve('.', '.output')
  }
}
```
and linking the nitro in with `npm link -D /path/to/nitro` gives me a working example :smiley:

**Comment by pi0** [comment]
Sorry for fast reply. Check https://github.com/unjs/nitro-preset-starter/tree/nuxt for a nuxt3 starter with custom preset. You can try implementation with it.

**Comment by Mastercuber** [comment]
I created a [repo](https://github.com/Mastercuber/nitro-preset-node-cluster) from the template and invited you to collaborate.

The [entry](https://github.com/Mastercuber/nitro-preset-node-cluster/blob/main/preset/entry.ts) should be the equivalent of the `node-cluster` entry. I don't know what the worker file is in the preset template. 

This PR seems like one way starting a cluster. The worker file is the [`node-cluster.ts`](https://github.com/unjs/nitro/pull/455/files#diff-cd3e8cfe1670c288f42638e780adfc60eb13f37c918de493c07a1529df299c58) file in the `src/runtime/entries` directory. Like for all other presets the entry point (`server.listen` etc.) are in this files.

Do you think it's better to create an extra preset for the cluster, instead of integrating it into nitro?

**Comment by pi0** [comment]
Thanks!  And yes this definitely worth to be a built-in preset for cluster support. It was a long time I wanted that thanks for helping on this ❤️ 

Will check your repo soon. I made it because you asked for a way to try on Nuxt as preset. There is another `nuxt` branch too in starter you could use to test against nuxt rc.9.

**Comment by Mastercuber** [comment]
> I made it because you asked for a way to try on Nuxt as preset. There is another `nuxt` branch too in starter you could use to test against nuxt rc.9.

Thanks for that, but just linking the local project in was enough to use the preset in a nuxt3 project.

**Comment by Mastercuber** [comment]
> There is another `nuxt` branch too in starter you could use to test against nuxt rc.9.

I will try testing against rc.9

**Comment by Mastercuber** [comment]
@pi0 I've created a working example on the starter `nuxt` branch. Should I create a PR for that from my fork, or can I push to the `nuxt` branch?

**Comment by Mastercuber** [comment]
Here is a [`node-cluster-preset`](https://github.com/unjs/nitro-preset-starter/pull/2) example based on the [`nitro-preset-starter`](https://github.com/unjs/nitro-preset-starter)

**Comment by pi0** [comment]
Thanks for helping on this @Mastercuber. I've added docs and couple of reactors to resuse `node-server` as much as possible. PR more than welcome to improve cluster preset 🚀

**Pull request merged**
