### PR TITLE
chore: remove lagon

### PR DESCRIPTION
**Pull request by maximepvrt**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by maximepvrt** [comment]
@pi0 I haven't deleted the page to https://nitro.unjs.io/deploy/providers/lagon(which doesn't work anyway) yet. Should it be kept or redirected to https://nitro.unjs.io/deploy

**Comment by maximepvrt** [comment]
> This means Lagon will be ending services. All projects on Lagon should be 100% compatible with Vercel Functions. If you are having trouble migrating, please do not hesitate to reach out. If you had access to Lagon Alpha, your projects will be offline on 03/01/2024.

Lagon mail received Dec 14  2023, 4:24 p.m.

I just thought it was an easy and helpful contribution to clean up

**Comment by pi0** [comment]
Thanks for clearify. I imagined it would be alive for few months more in alpha if completely out of service we can remove it 👍🏼

**Review by pi0 — APPROVED** [review]

**Comment by maximepvrt** [comment]
@pi0 and I delete this page?  https://github.com/unjs/nitro/blob/main/docs/2.deploy/20.providers/lagon.md

> @pi0 I haven't deleted the page to https://nitro.unjs.io/deploy/providers/lagon (which doesn't work anyway) yet. Should it be kept or redirected to https://nitro.unjs.io/deploy

**Pull request merged**
