### PR TITLE
fix(firebase): use correct key when importing firebase `httpsOptions`

### PR DESCRIPTION
**Pull request by luc122c**
### 🔗 Linked issue

fix https://github.com/unjs/nitro/issues/1655
https://github.com/unjs/nitro/pull/1657
https://github.com/unjs/nitro/pull/1556
https://github.com/unjs/nitro/pull/1555

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The correct key is `httpsOptions`, however, `httpOptions` was being pulled in. I searched for `httpOptions` and this appeared to be the only remaining instance. I believe this is the root fix for https://github.com/unjs/nitro/issues/1655

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by posva — APPROVED** [review]

**Comment by Hebilicious** [comment]
@posva do we need both setGlobalOptions and the options being passed there ?

**Comment by luc122c** [comment]
@Hebilicious I think #1657 is a workaround and would no longer be required. [This if statement](https://github.com/unjs/nitro/pull/1657/files#diff-72cb7be3bd5c0c59ef0494f431d02d876861049ce81e04c52da936122ac5d640R10) pulls from `httpsOptions`, which is the correct key, which is probably why it works. Setting the global options should not be necessary.

**Comment by posva** [comment]
I don’t think both are needed but since it was in docs I supposed the préfères way just changed and using the global options changed

**Comment by y-takebe** [comment]
Hi everyone!

I have confirmed that the code modified in this PR works as expected with `regions`, `minInstances`, etc. In this case,`setGlobalOptions` is not needed.

Alternatively, I have also confirmed that setting all options in `setGlobalOptions` works fine.

```typescript
setGlobalOptions(
  firebaseConfig.httpsOptions
);

export const __firebaseServerFunctionName__ = onRequest(
  {
    // Must be set to public to allow all public requests by default
    invoker: "public",
  },
  toNodeListener(nitroApp.h3App)
);
```

There is no need to have both, so choose one or the other.

**Review by pi0 — APPROVED** [review]
Thanks ❤️ I appreciate if you can confirm this PR using edge release channel if had a chance.

**Comment by luc122c** [comment]
@pi0 I'm on the edge release `Nuxt 3.7.0 with Nitro 2.6.3-28226639.ab15724` but my output is still showing the incorrect `httpOptions`. I deleted `node_modules`, `yarn.lock`, `.nuxt` and `.output` and did a fresh build but my  `.output/server/chunks/nitro/firebase-gen-2.mjs` still looks like this:

```js
const nitroApp = createNitroApp();
const useNitroApp = () => nitroApp;

const firebaseConfig = useAppConfig().nitro.firebase;
const server = onRequest(
  {
    // Must be set to public to allow all public requests by default
    invoker: "public",
    ...firebaseConfig.httpOptions
  },
  toNodeListener(nitroApp.h3App)
);
```

The Nitro config for this project is:
```ts
  nitro: {
    preset: "firebase",
    firebase: {
      gen: 2,
      nodeVersion: "18",
      httpsOptions: {
        region: "us-east1",
      },
    },
  },
  ```
  Any ideas on what to check?

**Comment by pi0** [comment]
@luc122c Are you using `resolutions` field? (feel free to DM me `@pi0` in discord!)

**Comment by luc122c** [comment]
@pi0 , no it's in the `devDependencies`. I've messaged you :)

**Pull request merged**
