### PR TITLE
feat: experimental `/_nitro/openapi.json` and `/_nitro/swagger` endpoints for dev mode

### LINKED ISSUE #3: Inspector
List all possible API routes as `/` or `/_nitro` and another runtime state of nitro. This can be initially implemented as a devserver feature.

### LINKED ISSUE #4: swagger API
expose swagger compatible API from dev server based on handler defenitions.

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

Resolves #3 
Resolved #4

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR exposes available routes and an initial meta using [Open API 3 standard](https://www.openapis.org/).

It exposes two endpoints for development:
- `/_nitro/openapi.json`: JSON response that can be integrated with external tools and setups such as Postman and Nuxt devtools to access available routes meta (/cc @antfu)
- `/_nitro/swagger`: A basic UI that makes local debugging easier

This feature opens the next steps in supporting generic and extendable route meta via a well-defined standard.

image

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by antfu** [comment]
That would be great! 🔥

**Comment by septatrix** [comment]
Hot damn, I forgot I even commented on that issue but it has just become relevant again for a project. Will definitely check it out ASAP (which might sadly not be too soon as I'm quite busy :/)!

**Comment by memic84** [comment]
Great feature!

It seems that the port 3000 in swagger is hardcoded, and the the port used in Nuxt. I am using port 3001 for this application, and the try out calls, won't work that way.

Is this a bug, or just wrong configuration of nitro on my part?

**Comment by septatrix** [comment]
I guess https://github.com/unjs/nitro/blob/4111798a09fde7bf5916500637e27d6acc0189d1/src/runtime/routes/openapi.ts#L20 should reuse the host+port where the application is exposed

**Comment by GionRubitschung** [comment]
I have found some problems using this.

Generating the json works, although with some errors. When opening the swagger page I get a json syntax error. I believe this comes from swagger itself. When copying the generated schema into the online swagger editor it has errors. The versioning and parameters are missing an option.

https://github.com/unjs/nitro/blob/2ad43894a6039207fd535d7fdc30ba92d4847ee6/src/runtime/routes/openapi.ts#L16
In the code the version is given as null but the [openapi specs](https://spec.openapis.org/oas/latest.html#infoVersion) are given this as required

Regarding the parameters openapi states this:
```
A parameter MUST contain either a schema property, or a content property, but not both.
```
See [here](https://spec.openapis.org/oas/latest.html#fixed-fields-9)

When generating the paths, these properties are not set
https://github.com/unjs/nitro/blob/2ad43894a6039207fd535d7fdc30ba92d4847ee6/src/runtime/routes/openapi.ts#L42

It would be great if there would an option we can define openapi properties for ourself. Maybe directly in the routes via a openapi config object that gets automatically picked up by the feature?

**Comment by xieze** [comment]
I still don't understand how to use it, can you give me a sample code?

**Comment by xieze** [comment]
I still don't understand how to use it, can you give me a sample code?

**Comment by dnnaji** [comment]
Just update your Nitro config:

```
// https://nitro.unjs.io/config
export default defineNitroConfig({
  experimental: {
    openAPI: false,
  },
})
```

**Comment by PrimeTimeTran** [comment]
Hey there.

How do we define the params for routes?

I tried following the openapi specification and it doesn't update the UI or JSON.

```js
import _ from 'lodash'
/**
 * @swagger
 * /api/accounts:
 *   get:
 *     summary: Retrieve a list of accounts
 *     description: Get all users from the system
 *     responses:
 *       '200':
 *         description: A list of accounts
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   username:
 *                     type: string
 *                   balance:
 *                     type: string
 */
export default defineEventHandler(async (e) => {
  try {
    let { limit, page } = e.context
    let params = getQuery(e)
    const query = buildQuery(params)
    const fieldsToPopulate = [
      { from: 'users', localField: 'user' },
      { from: 'banks', localField: 'bank' },
      { from: 'branches', localField: 'branch' },
      { from: 'transactions', localField: 'transactions' },
    ]
    const pipeline = buildPipeline(query, page, limit, fieldsToPopulate)
    const results = await Account.aggregate(pipeline)
    let { data, totalCount, pageCount } = results[0]
    if (!_.isEmpty(totalCount)) {
      totalCount = totalCount[0].total
    }
    const response = {
      meta: {
        page,
        pageCount,
        totalCount,
      },
      data,
    }
    return response
  } catch (error) {
    console.log({
      error,
    })
  }
})
```

These routes don't get updated that that codedoc/comment.
```
http://localhost:3005/_nitro/swagger
http://localhost:3005/_nitro/openapi.json
```

Screenshot 2023-12-18 at 2 35 25 PM
Screenshot 2023-12-18 at 2 35 12 PM

Apologize if that's a WIP and is expected to not work yet. I read through the commit but wasn't sure as I'm not an expert on the openapi spec. 

TIA~!

**Comment by PrimeTimeTran** [comment]
Also are there plans to enable configuring which `openapi.json` file to use? 

If I understand correctly, it's generated via Nitro. 
If thats the case then my previous comment is brought up. Regardless, I feel it makes the code too verbose. 

I checked the discussions tab and only found [this](https://github.com/unjs/nitro/discussions/170).

My use case is I generating/build routes programmatically and would prefer to generate/build the `openapi.json` as well and then have nitro point toward that if possible.

**Comment by septatrix** [comment]
> How do we define the params for routes?
> Apologize if that's a WIP and is expected to not work yet.

It is still an experimental feature and to my knowledge there is no easy mechanism to hook into the generation, yet.

> Also are there plans to enable configuring which `openapi.json` file to use?

If you do not want to use the autogenerated one you could just serve a static file and register the UI endpoint manually.

> My use case is I generating/build routes programmatically and would prefer to generate/build the `openapi.json` as well and then have nitro point toward that if possible.

I assume that once https://github.com/unjs/nitro/issues/938 gets merged these features could be combined to infer the types of the OpenAPI spec automatically.

**Comment by numselli** [comment]
In the [v2.4.0 release notes](https://github.com/unjs/nitro/releases/tag/v2.4.0) it states `We are working to bring route-level meta definition for an even better and more detailed docs generator.` I was wondering what the status of that is?

**Comment by daviddomkar** [comment]
I would also like to be updated on the status of adding the route level meta definitions.

**Comment by csmikle** [comment]
I don't know if this is a good place to report this but, I am using this feature in a Nuxt project and it works as long as I'm using npm. When I run an identical project in Bun, I get the "Unable to render this definition. The provided definition does not specify a valid version field." Though openapi.json is requested and looks the same.

**Comment by Ismael-Rakotondrazaka** [comment]
> Hey there.
> 
> How do we define the params for routes?
> 
> I tried following the openapi specification and it doesn't update the UI or JSON.
> 
> ```js
> import _ from 'lodash'
> /**
>  * @swagger
>  * /api/accounts:
>  *   get:
>  *     summary: Retrieve a list of accounts
>  *     description: Get all users from the system
>  *     responses:
>  *       '200':
>  *         description: A list of accounts
>  *         content:
>  *           application/json:
>  *             schema:
>  *               type: array
>  *               items:
>  *                 type: object
>  *                 properties:
>  *                   id:
>  *                     type: integer
>  *                   username:
>  *                     type: string
>  *                   balance:
>  *                     type: string
>  */
> export default defineEventHandler(async (e) => {
>   try {
>     let { limit, page } = e.context
>     let params = getQuery(e)
>     const query = buildQuery(params)
>     const fieldsToPopulate = [
>       { from: 'users', localField: 'user' },
>       { from: 'banks', localField: 'bank' },
>       { from: 'branches', localField: 'branch' },
>       { from: 'transactions', localField: 'transactions' },
>     ]
>     const pipeline = buildPipeline(query, page, limit, fieldsToPopulate)
>     const results = await Account.aggregate(pipeline)
>     let { data, totalCount, pageCount } = results[0]
>     if (!_.isEmpty(totalCount)) {
>       totalCount = totalCount[0].total
>     }
>     const response = {
>       meta: {
>         page,
>         pageCount,
>         totalCount,
>       },
>       data,
>     }
>     return response
>   } catch (error) {
>     console.log({
>       error,
>     })
>   }
> })
> ```
> 
> These routes don't get updated that that codedoc/comment.
> 
> ```
> http://localhost:3005/_nitro/swagger
> http://localhost:3005/_nitro/openapi.json
> ```
> 
> Screenshot 2023-12-18 at 2 35 25 PM Screenshot 2023-12-18 at 2 35 12 PM
> 
> Apologize if that's a WIP and is expected to not work yet. I read through the commit but wasn't sure as I'm not an expert on the openapi spec.
> 
> TIA~!

It's 2024, but still no news about that

**Comment by ssw1992** [comment]
I'm nearly driven to despair by @scalar/scalar, a persistent hardcoded bug that's remained unresolved for months. If this resolves it, I'll be immensely pleased.

**Pull request merged**
