### PR TITLE
chore(starter): add prepare command to starter

### PR DESCRIPTION
**Pull request by Barbapapazes**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adding a prepare script could help user to have generated types right after an installation.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
I think it is a good idea to add prepare to the starter templates but this `package.json` is not for starter it is main `nitro` package which can be used also as a library (for Nuxt).

**Comment by Barbapapazes** [comment]
> I think it is a good idea to add prepare to the starter templates but this `package.json` is not for starter it is main `nitro` package which can be used also as a library (for Nuxt).

Do I have to make this PR somewhere else? Not sure to have fully understand where to find the starter 🤔

**Comment by pi0** [comment]
Sorry for confusions. Starter is kinda hidden right now! It is in the same repo but in `starter` branch (https://github.com/unjs/nitro/tree/starter). You need to switch to this branch and then make a pull request against it.

**Comment by pi0** [comment]
Sorry my bad! You made it right 👍🏼

**Pull request merged**
