### PR TITLE
feat: add `iis` preset

### LINKED ISSUE #1034: IIS deployment information
### Describe the feature

It would be nice to have ISS added to the nitro provider list.

### Additional information

- [X] Would you be willing to help implement this feature?

### LINKED ISSUE #1187: [DOC] IIS Support
### Describe the feature

Please add 
https://github.com/nuxt/framework/commit/ede534847831f46c45089a122d19b083d2ae26c7

to your documentation. We had our app running with IIS10 + nuxt2 and had no problem at all. With Nuxt3 we struggled, but that documentation of the archived repo helped us alot!

Could you please add this to the Nitro Docs? I would also add a Issue to the main nuxt 3 repo, since many users asked in that repo for IIS documentation.

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by antony-k1208**
### 🔗 Linked issue

Resolves #1034
Resolves #1187 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

It resolves #1034. Adds IIS to the list of providers. I am not 100% sure if it is okay like that, because there is no preset for it.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for the PR. I think we can also introduce a preset for IIS generating `web.config` file.

**Comment by antony-k1208** [comment]
> Thanks for the PR. I think we can also introduce a preset for IIS generating `web.config` file.

Would love to do that. Can you tell me where I might find something similar?

**Comment by jim55167** [comment]
When can the documentation be runtime？

**Comment by derHodrig** [comment]
https://github.com/nuxt/framework/commit/ede534847831f46c45089a122d19b083d2ae26c7


I would mention that piece. Its based on IISNode, as an alternative. (is tested with Nuxt 3 + Docus, worked.

**Comment by Hebilicious** [comment]
> Thanks for the PR. I think we can also introduce a preset for IIS generating `web.config` file.

I've created an issue for an IIS preset : https://github.com/unjs/nitro/issues/1365
I am not a IIS user, but I assume that most users will want to overwrite the preset by passing a custom `web.config`.
In the meantime I think we can just update the docs.

**Review by Hebilicious — APPROVED** [review]
Moved to node section, and added information about IISnode

**Comment by jim55167** [comment]
I am using Nuxt 3.x version and I am following the documentation "Using IIS" to deploy my application. However, I am not sure where I made a mistake as it keeps showing a 404 Page not found error.

**Comment by Hebilicious** [comment]
@jim55167 can you try the other set of inscription that uses iis node and report back please ?

**Comment by jim55167** [comment]
@Hebilicious 
Adding a node was successful. It appears to be an issue with my settings, sorry.

螢幕擷取畫面 2023-07-05 163818

**Review by pi0 — CHANGES_REQUESTED** [review]
> Thanks for the PR. I think we can also introduce a preset for IIS generating web.config file

As a preset, we need to generate configuration file

**Comment by jim55167** [comment]
Good！
I hope to have deployment documentation as soon as possible to help developers who use Microsoft IIS resolve their issues.
Thank you all for your contributions and efforts

**Comment by Hebilicious** [comment]
> Good！ I hope to have deployment documentation as soon as possible to help developers who use Microsoft IIS resolve their issues. Thank you all for your contributions and efforts

We've decided to directly add a IIS preset which can be tested, to make sure that the deploy documentation doesn't get out of date. In the meantime you can refer to the docs directly in this PR.

**Comment by pi0** [comment]
Hi dear @antony-k1208. Thanks again for working on this PR. In order to move this forward, we need to make a dedicated preset. I have made a new issue #1427 with details of the task and will try to also implement and test it myself if can setup an ISS server (or feel free to do same). Your credits on final commit will be preserved of course ❤️

**Pull request closed without merging**
