### PR TITLE
feat(cloudflare-pages): improve cloudflare-pages adaptor to use dynamic imports

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
> **Warning**
>  Opening this as a draft since it looks like wrangler needs a small tweak to enable this: https://github.com/cloudflare/workers-sdk/pull/3707

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Update the Cloudflare Pages to use dynamic imports instead of bundling all the js into a single `_worker.js` file, this should make the adapter more performant and potentially reduce startup time

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Hebilicious** [comment]
I'll tag this as pending until https://github.com/cloudflare/workers-sdk/pull/3707 is merged 👍🏽

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks for the PR and followups dear @dario-piotrowicz ❤️ I have merged your work into #1172 from @danielroe to track both module and pages enabling from one place.

**Comment by dario-piotrowicz** [comment]
Hi @pi0 I did open this PR separately because the pages dynamic imports should be available very soon (after 
https://github.com/cloudflare/workers-sdk/pull/3707 is merged and a new version of wrangler is released)

Unfortunately I don't have an ETA as to when this is going to be available for workers.

So I was hoping that we could start using dynamic imports in the pages adaptor now and then do that in the module worker adaptor whenever possible.

If you believe that the two adaptors should be updated simultaneously I understand :slightly_smiling_face: 
(but again I am not sure when the worker lazy loading will be properly supported :sweat:)

**Comment by pi0** [comment]
Oh, thanks for the explanations wasn't aware of separate roadmaps. I can happily reopen here to speed it up or merge daniel's PR via an opt-in futuristic flag to make sure nitro is really already (and somehow locally tested).

Also BTW we have an UnJS discord channel for team communications. Would you be interested to join? (please DM me at pi0)

**Comment by dario-piotrowicz** [comment]
@pi0 just pinged you on discord 🙂

Regarding Pages and Workers sorry my bad for not mentioning anything in the PR's description 🙇 

Regarding this PR vs merging Daniel's I'm fine with whatever you prefer 🙂 (as long as we don't break the Workers adaptor naturally), although we can't test the lazy loading worker adaptor right now and be sure that it is actually fully ready (since there's not yet a wrangler built which fixes the workers' lazy loading [issue](https://github.com/cloudflare/workers-sdk/issues/3074)), so if we were to go with Daniel's PR there might still be a small chance that things will still need to be tweaked later on (which again, it's not terrible and I'd be fine with if that's an acceptable situation).

**Pull request merged**
