### PR TITLE
docs: upgrade to docus 2.0

### PR DESCRIPTION
**Pull request by Atinux**
WIP :)

### CODE REVIEW

**Comment by Tahul** [comment]
Hey :)

I migrated landing page on a fork as I have no rights to push directly on this branch!

I am targeting this branch with my fork, so feel free to merge it so we can preview it. 😄

**Comment by bdrtsky** [comment]
I suggest to update primary color tokens. They are way too linear for Docus. Can't push to branch, so I put them here

```
primary: {
      50: "#FFF6F7",
      100: "#FFEDEE",
      200: "#FFDBDE",
      300: "#FFBFC5",
      400: "#FFA5AC",
      500: "#FB848E",
      600: "#DD717A",
      700: "#A34F57",
      800: "#441F23",
      900: "#1F0E10",
    }
```

**Comment by bdrtsky** [comment]
Screenshot 2023-06-29 at 16 53 45

For the visual reference: left is old palette, right is the one updated.

**Comment by Atinux** [comment]
Could you share the updated `tokens.config.ts` @bdrtsky ?

**Comment by bdrtsky** [comment]
I can open PR to `docs/docus-2` branch (since I can't push into it). There's also some updates to landing cards layout, and some small improvements @Atinux

**Comment by Barbapapazes** [comment]
Hello, don't you have an option to keep the toc space? In fact, if you take a look at this page, https://unjs-nitro-pnhbxd5xr-nuxt-js.vercel.app/guide/cache and this page https://unjs-nitro-pnhbxd5xr-nuxt-js.vercel.app/guide/configuration, you will see that the content moves a bit to the right because the toc disappears. This, in my opinion, makes reading more complex.

**Comment by Atinux** [comment]
Agree, closing this PR since we are rewritting Docus without Tailwind right now.

**Pull request closed without merging**
