### PR TITLE
feat: possibility to render directly to stdout and render cli command

### PR DESCRIPTION
**Pull request by jrutila**
### 🔗 Linked issue

#2466 

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added a new option to `nitro.prerender` called `stdout` (default: false). When that option is set, the routes are generated to console output instead of written to files.

Added a new command line tool called `render` that will render a single given route. It can have an option `--stdout` and then it will output the route to console.

### 📝 Checklist
- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jrutila** [comment]
You can test this feature like this:
- Add a route to `playground/routes/`, for example `abba.ts` that has this
```
export default eventHandler(async (event) => {
  return "AbbA";
});
```
- run `pnpm nitro build --dir playground` to first build the playground
- run `pnpm nitro render --dir playground --stdout abba` 
- you should now see "AbbA" in the output of the previous render command

**Comment by jrutila** [comment]
You can test this feature like this:
- Add a route to `playground/routes/`, for example `abba.ts` that has this
```
export default eventHandler(async (event) => {
  return "AbbA";
});
```
- run `pnpm nitro build --dir playground` to first build the playground
- run `pnpm nitro render --dir playground --stdout abba` 
- you should now see "AbbA" in the output of the previous render command

**Comment by jrutila** [comment]
Is there possibility to get this forward? It will fall behind the main, again. Please let me know if something else is needed to get it merged.

**Comment by pi0** [comment]
Hi dear @jrutila thanks for your pull request and sorry for late review. I really appreciate it. ❤️ 

I cannot accept it as-is for some reasons:

- Nitro has already a CLI preset intended for same thing (standalone output that can render to stdout without depending in nitro builder core) -- PR welcome to improve it
- Before thinking about considering a new sub-command like this, we need to implement a _smart rebuild_ functionality that avoid nitro rebuild if source has not been changed to avoid extra rebuilds otherwise it will be an impractical feature
- The proposed API should (`prerenderRoute()`) also be possible with programmatic API to be usable with other meta frameworks used in conjunction with nitro

For maintenance i am closing this PR (for now) let's keep tracking about the idea via #2466 i definitely love to work on this in the futur.

**Pull request closed without merging**
