### PR TITLE
feat: use pre-bundled `swagger-ui-dist`

### PR DESCRIPTION
**Pull request by HigherOrderLogic**
### 🔗 Linked issue

Resolve https://github.com/unjs/nitro/issues/1757.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Use pre-bundled package `swagger-ui-dist` for offline usage.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by septatrix** [comment]
Having this as a non-optional dependency is a drawback in terms of bundle size as not everyone will need this. I think the better way would be to allow customization of the URL/endpoint (or add a section to the documentation of how to add a UI route and remove the UI from the builtin routes altogether). In the end there are also alternative UIs like redoc and scalar which people want to use (and the [comment from @pi0](https://github.com/unjs/nitro/issues/1757#issuecomment-1735452600) that unjs *might* develop something similar in the future as well)

**Comment by HigherOrderLogic** [comment]
Swagger route is only added in dev build, hence the production bundle size wont be affected.

**Comment by septatrix** [comment]
> Swagger route is only added in dev build, hence the production bundle size wont be affected.

But the download size will. It an additional 10MB on top of what currently seems to be ~180MB for nuxt itself. This slows down installation, CIs, impact people with metered bandwidth etc. – all for something which many people might never use.

**Comment by pi0** [comment]
Thanks for PR. Keeping this idea on hold since there are install size concerns + we are introducing new uis (`/_nitro/scalar`)

**Pull request closed without merging**
