### PR TITLE
refactor: tidy up

### PR DESCRIPTION
**Pull request by Simon-He95**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by manniL** [comment]
Thanks for your effort but I feel like the proposed improvements make the code less readable than before. Similar to previously proposed PRs. 🙁

**Comment by Simon-He95** [comment]
> Thanks for your effort but I feel like the proposed improvements make the code less readable than before. Similar to previously proposed PRs. 🙁

Why is it more difficult to understand, I just combined the conditions of the same return result, and then replaced the for that satisfies the conditions with some

**Comment by manniL** [comment]
Because chained logical statements can make code less readable. I'd rather have longer code that shows that the statements are separate concerns / cases than figuring out these cases in a longer chained or-statement.

If necessary, some conditions would even have an own variable that describes it. Longer code, but easier to understand.

**Comment by Simon-He95** [comment]
I think finding a unique condition for returns, which just satisfies some function, can express this meaning. In addition, since they all return false, it will be more concise to use the if condition to merge and express in a new line. Returning in this case, I don't think he loses readability, it's ok, everyone's understanding is different.

**Pull request closed without merging**
