### PR TITLE
fix(worker): preserve esmodule symbol for dynamic imports

### PR DESCRIPTION
**Pull request by 20051231**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

iife inlined all dynamic imports but name tag is not preserved so it is not recognized by vue defineAsyncComponent correctly as an esmodule for all dynamic chunks such as pages / layouts.

Enabling the rollup option fixes the issue.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

https://github.com/nuxt/framework/issues/5996

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Nice catch!

**Note**: this also affects `vercel-edge` and `netlify-edge` (in addition to cloudflare) which will currently be broken without this fix.

**Comment by riderx** [comment]
I tried to add the config in my nuxt app here https://github.com/riderx/captime-website/commit/da09bdb2c57724355ac2b023770fbbc0b8a811ce
and still get issue at runtime in netlify-egde
Screenshot 2022-07-22 at 14 32 59
Screenshot 2022-07-22 at 14 33 13

I'm not sure that exactly related.

**Review by pi0 — APPROVED** [review]
Thanks!

**Comment by pi0** [comment]
I couldn't test it but trust works. For the future fixes, it would be nice to link nitro PRs with minimal reproduction (of a nitro app) 🙏🏼

**Comment by marshallswain** [comment]
Thank you.  This solution fixed my cloudflare-deployed Nuxt app.

**Pull request merged**
