### PR TITLE
feat: add `defineNitroErrorHandler` type helper

### LINKED ISSUE #1922: Provide `defineErrorHandler` when writing a nitro error handler
### Describe the feature

A lot of configurable functionality in nitro uses the "definer" pattern (`defineNitroConfig`, `definePlugin`, etc.) to help users make type-safe definitions, provide IDE completions and you could even backport breaking changes by adding logic to the definer function that upgrades a definition passed to it.

I'd say it is probably one of the most important features, as it creates a very robuust workflow for writing (runtime) code.

Strangely enough there is no such definer function for an error handler.
Instead there is the following example set by the docs:

```typescript
import type { NitroErrorHandler } from 'nitropack'

export default <NitroErrorHandler> function (error, event) {
  event.res.end('[custom error handler] ' + error.stack)
}
```

[Link to NitroErrorHandler definition](https://github.com/unjs/nitro/blob/811d693ddc13d38e2fdd5e6d3000fad7d5ca4474/src/types/handler.ts#L47)

I believe this to be a mistake.
The error handler (as far as I can tell) has the same runtime as event handlers, plugins and so on.

The definer would look something like the following:

```typescript
export function defineErrorHandler(handler: NitroErrorHandler) : NitroErrorHandler {
  return handler;
}
```

Required changes:
1. Add the definer function
2. Make the definer part of the auto-imports
3. Update the [documentation of config#error-handler](https://github.com/unjs/nitro/blob/811d693ddc13d38e2fdd5e6d3000fad7d5ca4474/docs/content/3.config.md?plain=1#L287)

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by passionate-bram**
### 🔗 Linked issue

#1922 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

1. Feat: Creates a `defineErrorHandler` function that follows the definer pattern.
2. Feat: Enlist the `defineErrorHandler` function in the auto-import list.
3. Docs: Change example of `errorHandler` on the Configuration page, to use the new function.
4. Docs: Describes the expected behaviour of an `errorHandler` in a bit more detail

These changes are needed as described in #1922 I believe the "definer pattern" (I guess it is the factory pattern but the `defineX` gives it a nice recognizable shape) is an important feature of nitro and provides good ergonomic value to users of the library.

Please note that I made several smaller commits, feel free to pick and choose the changes to make it fit with the project as a whole.

Resolves #1922 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks! Maybe for consistency with type name we can name if decineNitroErrorHandler?

**Comment by passionate-bram** [comment]
> Thanks! Maybe for consistency with type name we can name if decineNitroErrorHandler?

As package maintainer the API (incl naming conventions) would be your decision / responsibility.
I'll leave that for the you to decide, feel free to let me know if you'd like me to make changes to the PR.

**Review by pi0 — APPROVED** [review]
Thanks!

**Comment by passionate-bram** [comment]
I see you added https://github.com/unjs/nitro/pull/1923/commits/355ea896f2e57ccf23d9d286119165e5312d8927 in order to reduce the size of the merge. I can rebase the other commit out as well, then it won't be in the history anymore

**Comment by pi0** [comment]
> I see you added https://github.com/unjs/nitro/commit/355ea896f2e57ccf23d9d286119165e5312d8927 in order to reduce the size of the merge. I can rebase the other commit out as well, then it won't be in the history anymore

Thanks no need we always squash :)

**Pull request merged**
