### PR TITLE
feat: resolve actual subpaths before guessing

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This resolves actual subpaths rather than guessing, so (for example) `node-fetch-native/dist/polyfill.mjs` can correctly be resolved to `node-fetch-native/polyfill` and back again.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
If you like this approach we can also extract into a `mlly` util.

**Comment by pi0** [comment]
A refactor to mlly would be nice idea for reverse resolving subpaths 👍🏼

**Comment by danielroe** [comment]
extracted:
- [ ] https://github.com/unjs/pkg-types/pull/47
- [ ] https://github.com/unjs/mlly/pull/89

**Comment by Hebilicious** [comment]
@danielroe is this ready to review ?

**Comment by danielroe** [comment]
It is.

**Review by Hebilicious — DISMISSED** [review]

**Comment by Hebilicious** [comment]
Had to create a new branch to fix the conflicts. You can force push from there https://github.com/unjs/nitro/pull/1395
This looks good to me, altough I'm not really a rollup wizard like you 💇🏽

**Comment by danielroe** [comment]
I don't believe there are any conflicts in this branch

**Comment by Hebilicious** [comment]
@danielroe You're right, I got confused because these 2 diffs are not the same 
https://github.com/unjs/nitro/compare/main...feat/actual-subpaths
https://github.com/unjs/nitro/compare/main...feat-actual-subpaths-clean
Maybe something wrong with the github ui ?

**Comment by Hebilicious** [comment]
Ah yes ignore me 🤦 GitHub UI fooled me

**Review by pi0 — APPROVED** [review]

**Pull request merged**
