### PR TITLE
fix(prerender): remove `baseURL` from generated file paths

### PR DESCRIPTION
**Pull request by farnabaz**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Generating a project using custom baseURL results unwanted directory inside `.output/public`.
For example, if you set `baseURL = romi-project`, you will see a `romi-project` directory in the generated website. https://github.com/hacknug/romi-project/tree/gh-pages

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by farnabaz** [comment]
Maybe I'm wrong about the behavior of Nuxt pretender. Should it generate a subdirectory inside `.output/public`?

What I think is that the generated website should not have a subdirectory inside it. When I set `baseURL` in nuxt config, I want to deploy it under a directory in a host. Generating this subdirectory causes duplicate `baseURL`

Feel free to close this PR if it does not look good :)

**Comment by farnabaz** [comment]
Yes removing baseURL from `filePath` will do the trick too.

But I think the best way is to remove baseURL from routes and add it in the fetch call. This way we can support URLs like this

```
/baseUrl/baseUrl/something
```

Imagine user have a page with same name is baseURL

**Comment by danielroe** [comment]
I think that's a good point. But we will still need to update the filenames

**Review by danielroe — APPROVED** [review]

**Review by pi0 — APPROVED** [review]
LGTM. We might add a symbolic link to avoid breaking change and allow cases when public structure is expected to have base url

**Pull request merged**
