### PR TITLE
docs(deploy): add `platform.sh`

### PR DESCRIPTION
**Pull request by oritwoen**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I've been using `platform.sh` recently and thought I'd add some information about deploy there.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by oritwoen** [comment]
I updated the information and configuration to Nitro 2.6 requirements.

- https://unjs.io/blog/2023-08-25-nitro-2.6#default-persistent-data-storage

**Comment by oritwoen** [comment]
@pi0 I'm changing it to draft until Nuxt 3.8, Nitro 2.7 and the stable version of @nuxt/image come out.

With the number of changes that are to be made in the new releases, I am almost sure that it will be necessary to slightly modify the deployment configuration to platform.sh.

**Comment by pi0** [comment]
Thanks for your working on this. BTW we don't block Nuxt/Nitro releases. They are always in parallel and platform support is open to every one/framework.

**Comment by oritwoen** [comment]
I may have expressed myself incorrectly. In `platform.sh` you can use `node` or `bun` and in the configuration from this PR everything works beautifully.

However, I tried to run `@nuxt/image` on this platform and it gives me some problems, I have not yet figured out whether it is related to ipx or the module itself. For each use of disk writing, you need to mount paths in the configuration, and for reading (e.g. ipx path) that returns media, slight configuration changes are also required. I may also simply not have enough RAM on the instance, I'm checking it.

I also saw in the latest RC for `image` that a potentially stable version will be integrated into Nuxt as an internal module without additional installation.

Hence, I wanted to wait and test it after the release of new versions of `@nuxt/image` and `Nuxt 3.8` whether the problem will still occur with new stable releases.

**Comment by oritwoen** [comment]
I only had problems with `@nuxt/image`, everything else works great. 

I have been using this setup for over a month.  You made me realize that I shouldn't have thought too much about it.  If you don't have any additional comments, feel free to merge :)

**Review by pi0 — APPROVED** [review]
Sorry for delay. i have pushed some updates to simplify (but haven't tested feel free to amend PR changes). Lets iterate 👍🏼

**Pull request merged**
