### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
### 📚 Description

Found few misspellings.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by pi0** [comment]
@szepeviktor BTW may i ask what tool you used to find typos?

**Comment by szepeviktor** [comment]
It is called typos.
https://github.com/crate-ci/typos
It is a single Rust binary.

**Comment by szepeviktor** [comment]
@pi0 `.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Chad Lew",
    "\\bSerKo\\b",
    "\\[[0-9a-f]{7,8}\\]",
]

[default.extend-words]

[default.extend-identifiers]
# Typos
"Github" = "GitHub"
```

**Pull request merged**
