### PR TITLE
feat: experimental `cloudflare-durable` preset

### PR DESCRIPTION
**Pull request by pi0**
This PR adds a new experimental `cloudflare-durable` (based on `cloudflare-module`) preset which allows:

- out of the box websocket support with pub/sub
- `cloudflare:durable:init` and `cloudflare:durable:alarm` for custom hooks via plugins

Not documenting yet to experiment

### CODE REVIEW

**Comment by CanRau** [comment]
Anything similar planned for [Workflows](https://developers.cloudflare.com/workflows/)?

**Comment by pi0** [comment]
Yes, actually for supporting workflows i might reiterate with another method of enabling durable for workers (via config)

**Comment by CanRau** [comment]
Sounds interesting looking forward, just getting started with Tanstack Start 🤓

**Comment by adamdehaven** [comment]
> Not documenting yet to experiment

@pi0 any idea when this is ready enough to utilize in a prod. project?

**Comment by estige** [comment]
thanks!

**Pull request merged**
