### PR TITLE
refactor: improve `esbuild.target` option handling

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/framework/issues/4771

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Context: https://github.com/nuxt/framework/issues/507

This sets esbuild target to currently minimum node version required for project, and removes the additional default set within the plugin.

https://esbuild.github.io/api/#target

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
We might set the default to a fixed value to avoid unpredictable behavior.

It is also not _solving_ linked issue. `import.meta.url` should be avoided regardless in runtime!

**Comment by danielroe** [comment]
Yes, agreed that's a separate issue. But I don't see a downside to defaulting to minimum supported node version. (We could then override in specific presets, e.g. for Cloudflare.) What do you think of the change?

**Comment by pi0** [comment]
No. Node.js should not be esbuild target! It will make strange issues when bundled. Let's track universal `import.meta` support via #181

**Comment by danielroe** [comment]
It is currently set to node12/esbuild2019. I think this should be changed.

**Comment by pi0** [comment]
It is always set to `es2019`. Migration to `es2020` is a good idea but I need to investigate more to ensure there would be no breaking changes. 

What is goal of this PR?

**Comment by danielroe** [comment]
If you want to stay on `es2019`, then I think the changes this PR makes are more in the nature of a tweak than a change.

However, `es2020` should be safe in node 14+. FWIW, I don't believe `node14.16.0` uses _node-specific_ APIs. It's just shorthand for the JS features supported in Node 14.16.0. (See [here](https://esbuild.github.io/content-types/#javascript) for details of the transforms.) What makes you think it would cause issues once bundled?

**Comment by pi0** [comment]
Migration from es2019 to es2020:

- Removes optional chaining / nullish  coalescing transform. It can break some targets
- Adds `import.meta`. It is not safe to use even within context of Node for purpose of `import.meta.url`. (therefore https://github.com/unjs/nitro/issues/181)

What else this change would solve?

image

**Pull request merged**
