### PR TITLE
feat: support async plugins

### LINKED ISSUE #915: Make plugins async
For the benefit of bootstrapping plugins it is usefull to make plugins load async.

https://github.com/unjs/nitro/blob/ed3a48026e8a27ecfb86e406ba39bdeb418f8573/src/runtime/app.ts#L89-L91

Can someone explain to me if there is a good reason to load plugins synchronously?

### PR DESCRIPTION
**Pull request by MarijnMensinga**
### 🔗 Linked issue

#915

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Plugins should be loaded async to make the plugins bootstrap propperly. 

This fixes potential race-conditions when creating plugins that are called before they are bootstrapped correctly.

Resolves #915

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly. (not needed)

### CODE REVIEW

**Comment by pi0** [comment]
This is a nice feature to have! The main issue is that support for top-level await is limited and many providers are currently depending on nonasync API. 

Putting a pending label for now. It is likely we could only support async plugins in Nitropack v3 and some breaking changes.

**Comment by Hebilicious** [comment]
@pi0 Can't we work around the issue with a closure ? 

```ts
const createNitroApp = () => {

const installPlugins = async () => {
  for (const plugin of plugins) {
    await plugin(app);
  }
}

installPlugins()
}
```

**Comment by pi0** [comment]
@Hebilicious no we lose order this way.

**Comment by pi0** [comment]
Thanks for PR again dear @MarijnMensinga. It is not mergeable without breaking changes. Let's keep track via https://github.com/unjs/nitro/issues/915 (i might have some ideas to introduce as non breaking)

**Pull request closed without merging**
