### PR TITLE
fix: don't render json response if url contains `/api/`

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/19093

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Although a helpful idea, I think this is too broad a net for rendering an API response. Even routes starting with `/api` might still benefit from an HTML response if requested from a browser.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by dargmuesli** [comment]
Isn't that a breaking change? With Nuxt requests to `server/api` endpoint now return html instead of the expected json.

**Comment by danielroe** [comment]
~> see https://github.com/unjs/nitro/pull/969

**Comment by dargmuesli** [comment]
Thank you for the background, I see :+1:  Intuitively I'd expect "root" `/api` routes to keep the previous json behavior, not matter how they're accessed.

I have an endpoint that either returns a specific content type (`text/calendar`) or throws a `createError`. I'd expect json for errors, even when calling that endpoint by manual input into the browser's address bar.
I don't want to rename the endpoint to `*.json` as it can return a different mime type. I also don't want to set the `Content-Type` header manually before errors. I'm not sure if the cors-related fix will solve that question, but I'll try later :raised_hands: 
Is there something I should do instead? Maybe I don't see the obvious way to do it now.

**Comment by danielroe** [comment]
I understand what you mean, though equally I would not expect users to access an `/api/` endpoint directly in the browser and receive JSON (but only in the event of an error).

Would you open an issue to discuss adding a `.startsWith()` test? We might also consider allowing handlers to _indicate_ their preference somehow, or something else.

cc: @pi0 who may have a better idea.

**Comment by pi0** [comment]
Reverting in https://github.com/unjs/nitro/pull/971 for now.

**Comment by dargmuesli** [comment]
I've created https://github.com/unjs/nitro/discussions/978 as a place where a discussion can continue.

**Pull request merged**
